### ISSUE TITLE
Push Permission.

### ISSUE THREAD

**Issue by Zariweya** [JejuSoul/OBD-PIDs-for-HKMC-EVs#15]
Hi JejuSoul.

I modified your ioniq HEV PIDs to match with the Kia Niro HEV and PHEV models and made some testing with my car. At the moment I cloned your repo to https://github.com/Zariweya/OBD-PIDs-for-HKMC-EVs.

It's possible to merge the branches to continue working in this project? Or at least have push permissions to upload the files to your project, if you want.

Best regards

**Comment by ayokyun** [comment]
Make a pull request, then I'll merge it!

**Comment by Zariweya** [comment]
Done.

Regars.

**Comment by Zariweya** [comment]
I'm recreated the fork and made the pull request. Hope this time works.
