### ISSUE TITLE
Formula in xls sheet (spreadsheet_Ioniq_EV_BMS) is wrong

### ISSUE THREAD

**Issue by NatroNx** [JejuSoul/OBD-PIDs-for-HKMC-EVs#20]
Hi - the formula for Battery Current in "K17" is  "=REST(HEXINDEZ(H4&B5)+2^15;2^16)-2^15" but should be "=(REST(HEXINDEZ(H4&B5)+2^15;2^16)-2^15)*0.1" because the Value has to be divided by 10 to be valid.

regards

**Comment by JejuSoul** [comment]
Thanks. will fix that now.
