### ISSUE TITLE
No extended PID's in Torque Pro selectable

### ISSUE THREAD

**Issue by nightmare28** [JejuSoul/OBD-PIDs-for-HKMC-EVs#25]
Hello
I am driving a KIA HEV MY17, loaded all 4 extended pid's on my android device, put them in the right directory and added the 0_Niro_PIDs_final.csv in the menu. After returning to Torque home screen and live DataTab I cannot see this extended PID's to be added. Will test if ECU is connected on some PID's... I cannot understand what is going wrong, even I did everything according to the readme/manual.

**Comment by kardaman** [comment]
Hello
How did you solved the problem?

My problem is:

The import if the PIDs into torque is not working.

I can see the PIDs file names in the menu of torque.

If I click on them, the list is still empty.

If I click on other ﻿selectable "standard" files like "Ford (Incl PowerStroke)", PIDs getting filled into the list﻿

Do I do something wrong﻿?﻿﻿﻿﻿

Thanks
