### ISSUE TITLE
Kona EV error in formula for 45kw charge time

### ISSUE THREAD

**Issue by piec2** [JejuSoul/OBD-PIDs-for-HKMC-EVs#34]
There's a mistake for the Kona EV formula on the 004_CALC Estimated time 45kW 80% Charge
The formula currently states: (MAX(0:28*(0.8-(af/200)))/45)*60
But on the Kona EV, the battery has 64 kWh available and the formula should be:
(MAX(0:64*(0.8-(af/200)))/45)*60

Thanks!

**Comment by JejuSoul** [comment]
Thanks. I have corrected this. Can anyone confirm if this works?
